services:
  # postgres:
  #   image: postgres:15.9
  #   restart: always
  #   environment:
  #     - POSTGRES_USER=${POSTGRES_USER}
  #     - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  #     - POSTGRES_DB=${POSTGRES_DB_NAME}
  #   ports:
  #    - "5432:5432"
  #   volumes:
  #     - ./data/postgres/data:/var/lib/postgres/data
  #   healthcheck:
  #     test: [ "CMD-SHELL", "pg_isready", "-U ${POSTGRES_USER}", "-d ${POSTGRES_DB_NAME}" ]
  #     interval: 30s
  #     timeout: 10s
  #     retries: 5
  #     start_period: 80s

  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    container_name: minio_news_article
    command: server /data --console-address ":9001"
    env_file:
      - .env

  # portion_service:
  #   build:
  #     dockerfile: ./Dockerfile
  #     target: main
  #   restart: always
  #   ports:
  #     - "8003:8003"
  #   env_file:
  #     - .env